"""Add codepoint

Revision ID: 0957a0ef1f13
Revises: None
Create Date: 2016-05-23 08:39:23.072750

"""

# revision identifiers, used by Alembic.
revision = '0957a0ef1f13'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codepoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.Unicode(), nullable=False),
    sa.Column('quality', sa.Unicode(), nullable=True),
    sa.Column('country', sa.Unicode(), nullable=True),
    sa.Column('nhs_region', sa.Unicode(), nullable=True),
    sa.Column('nhs_authority', sa.Unicode(), nullable=True),
    sa.Column('county', sa.Unicode(), nullable=True),
    sa.Column('district', sa.Unicode(), nullable=True),
    sa.Column('ward', sa.Unicode(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(spatial_index=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codepoint_postcode'), 'codepoint', ['postcode'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codepoint_postcode'), table_name='codepoint')
    op.drop_table('codepoint')
    ### end Alembic commands ###
