"""added next_update metadata field in dataset

Revision ID: 140d7075ca9f
Revises: 203032fb2e94
Create Date: 2016-05-25 16:13:49.437817

"""

# revision identifiers, used by Alembic.
revision = '140d7075ca9f'
down_revision = '203032fb2e94'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('next_update_date', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'next_update_date')
    ### end Alembic commands ###
