"""Add carpark

Revision ID: 27f5e8750dd5
Revises: 0957a0ef1f13
Create Date: 2016-05-23 10:13:38.803997

"""

# revision identifiers, used by Alembic.
revision = '27f5e8750dd5'
down_revision = '0957a0ef1f13'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('operator', sa.Unicode(), nullable=True),
    sa.Column('scheme_status', sa.Unicode(), nullable=True),
    sa.Column('part_time_award', sa.Unicode(), nullable=True),
    sa.Column('phone', sa.Unicode(), nullable=True),
    sa.Column('street_1', sa.Unicode(), nullable=True),
    sa.Column('street_2', sa.Unicode(), nullable=True),
    sa.Column('street_3', sa.Unicode(), nullable=True),
    sa.Column('town', sa.Unicode(), nullable=True),
    sa.Column('county', sa.Unicode(), nullable=True),
    sa.Column('postcode', sa.Unicode(), nullable=True),
    sa.Column('physical_type', sa.Unicode(), nullable=True),
    sa.Column('payment_type', sa.Unicode(), nullable=True),
    sa.Column('number_of_spaces', sa.Integer(), nullable=True),
    sa.Column('disabled_spaces', sa.Integer(), nullable=True),
    sa.Column('cycles', sa.Unicode(), nullable=True),
    sa.Column('motobike', sa.Unicode(), nullable=True),
    sa.Column('cars', sa.Unicode(), nullable=True),
    sa.Column('bus', sa.Unicode(), nullable=True),
    sa.Column('coach', sa.Unicode(), nullable=True),
    sa.Column('truck_parking_area', sa.Unicode(), nullable=True),
    sa.Column('longitude', sa.Unicode(), nullable=True),
    sa.Column('latitude', sa.Unicode(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(spatial_index=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carpark')
    ### end Alembic commands ###
