"""change number_of_spaces to spaces in carpark model

Revision ID: 8eefc70c0433
Revises: 9645ccf2a414
Create Date: 2016-05-25 13:26:43.180016

"""

# revision identifiers, used by Alembic.
revision = '8eefc70c0433'
down_revision = '9645ccf2a414'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpark', sa.Column('spaces', sa.Integer(), nullable=True))
    op.drop_column('carpark', 'number_of_spaces')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpark', sa.Column('number_of_spaces', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('carpark', 'spaces')
    ### end Alembic commands ###
