"""Change carpark geog to a point

Revision ID: 900cc0763bda
Revises: 27f5e8750dd5
Create Date: 2016-05-23 10:21:39.712908

"""

# revision identifiers, used by Alembic.
revision = '900cc0763bda'
down_revision = '27f5e8750dd5'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpark', sa.Column('point', geoalchemy2.types.Geography(geometry_type='POINT', spatial_index=False), nullable=True))
    op.drop_column('carpark', 'geom')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpark', sa.Column('geom', geoalchemy2.types.Geography(srid=4326), autoincrement=False, nullable=True))
    op.drop_column('carpark', 'point')
    ### end Alembic commands ###
