"""add spend data

Revision ID: 9a782a36bc6f
Revises: 140d7075ca9f
Create Date: 2016-06-08 11:58:48.216973

"""

# revision identifiers, used by Alembic.
revision = '9a782a36bc6f'
down_revision = '140d7075ca9f'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('OrganisationLabel', sa.Unicode(), nullable=True),
    sa.Column('OrganisationalUnit', sa.Unicode(), nullable=True),
    sa.Column('TransactionNumber', sa.Unicode(), nullable=True),
    sa.Column('BeneficiaryName', sa.Unicode(), nullable=True),
    sa.Column('ExpenseType', sa.Unicode(), nullable=True),
    sa.Column('PaymentDate', sa.Unicode(), nullable=True),
    sa.Column('Amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spend')
    ### end Alembic commands ###
